services: 
  api:
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes: 
      - ./backend:/api
      - '/api/node_modules'
  client:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on: 
      - api
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:1000"
